version: '3.8'

services:
  sql_server_container:
    image: mcr.microsoft.com/mssql/server
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${DB_PASSWORD}
    ports:
      - "1433:1433"

  backend:
    build: ./backend
    env_file:
      - .env
    environment:
      - DB_CONNECT_STRING=Server=sql_server_container,1433;Database=${DB_NAME};User Id=${DB_USER_ID};Password=${DB_PASSWORD};TrustServerCertificate=True
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - JWT_ISSUER=${JWT_ISSUER}
      - JWT_AUDIENCE=${JWT_AUDIENCE}
      - JWT_EXPIRY_MINUTES=${JWT_EXPIRY_MINUTES}
      - REQUEST_LIMIT=${REQUEST_LIMIT}
      - LIMIT_ITEM=${LIMIT_ITEM}
      - SMTP_SERVER=${SMTP_SERVER}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_SENDER_EMAIL=${SMTP_SENDER_EMAIL}
      - SMTP_SENDER_PASSWORD=${SMTP_SENDER_PASSWORD}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - FACEBOOK_APP_ID=${FACEBOOK_APP_ID}
      - FACEBOOK_APP_SECRET=${FACEBOOK_APP_SECRET}
      - CORS_ALLOWED_ORIGINS =${CORS_ALLOWED_ORIGINS}
    ports:
      - "5000:8080"
    depends_on:
      - sql_server_container

  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
