services:
  backend:
    build: ./backend
    env_file:
      - .env
    environment:
      - MONGODB_CONNECTION_STRING=${MONGODB_CONNECTION_STRING}
      - MONGODB_NAME=${MONGODB_NAME}
      - REBUS_QUEUE_NAME=${REBUS_QUEUE_NAME}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - JWT_ISSUER=${JWT_ISSUER}
      - JWT_AUDIENCE=${JWT_AUDIENCE}
      - JWT_EXPIRY_MINUTES=${JWT_EXPIRY_MINUTES}
      - SMTP_SERVER=${SMTP_SERVER}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_SENDER_EMAIL=${SMTP_SENDER_EMAIL}
      - SMTP_SENDER_PASSWORD=${SMTP_SENDER_PASSWORD}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - FACEBOOK_APP_ID=${FACEBOOK_APP_ID}
      - FACEBOOK_APP_SECRET=${FACEBOOK_APP_SECRET}
      - ALLOWED_CORS=${ALLOWED_CORS}
      - FRONTEND=${FRONTEND}
      - APP_BASE_URL=${APP_BASE_URL}
      - GIT_TOKEN=${GIT_TOKEN}
      - GIT_USERNAME=${GIT_USERNAME}
      - GIT_REPO=${GIT_REPO}
    ports:
      - "5000:8080"

  # frontend:
  #   build: ./frontend
  #   ports:
  #     - "8080:80"
  #   depends_on:
  #     - backend
